# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 381031dc07674f11b1445e3f86e4447b351127713a67b12b559d990fcd0f73e5031657dae3262ccf07368ffc49dd0a0eb5f1f67e970f81dfc052d8bbfdded57c

test:
  secret_key_base: 175cd4a2d031c32b5c9ec1ea5ac67de329520827bdb3334cc4745fad694b0da177ad2842df3262d9c5f8222c8cdfe80a57f99ef061861d73174ba336a26a3ca1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
